### ISSUE TITLE
Support for remote flashing or via Home Assistant

### ISSUE THREAD

**Issue by mdimjasevic** [NabuCasa/sl-web-tools#5]
I access my home assistant remotely in the browser, i.e., it's not hosted on the machine I run my web browser on. Is there any chance you could support this use case of flashing a remote device? Alternatively, an even better option would be to have SL web tools integrated into Home Assistant so one can update the firmware from within the user interface.

**Comment by puddly** [comment]
The web tools require the SkyConnect to be plugged straight into the computer accessing the website. It isn't possible to connect to a remote serial port.

The web tools are actually just a browser-based wrapper around https://github.com/NabuCasa/universal-silabs-flasher, which *can* be installed within Home Assistant OS and used to flash firmware remotely.
